name: Generate Snake

on:
  schedule: # otomatis jalan tiap hari
    - cron: "0 0 * * *"   # jam 00:00 UTC (07:00 WIB)
  workflow_dispatch:      # bisa dijalankan manual
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: hakimxiao
          outputs: dist/snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
